Repository cyberark/conjur, pull requests merged in 2018-12, with the labels that each got.

#814 Fix Escaping for Audit Log Formatter
  CHANGELOG.md
  lib/logger/formatter/rfc5424_formatter.rb
  spec/logger_spec.rb
Labels: in progress, review

#818 Remove CloudFormation from Conjur
  CHANGELOG.md
  aws/cloudformation/conjur.yml
Labels: implementing, review

#822 cleanup the test driver script
  .dockerignore
  .gitignore
  CHANGELOG.md
  Jenkinsfile
  ci/docker-compose.yml
  ci/rspec-audit/migratedb
  ci/test
  cucumber/api/features/authn_restricted_to.feature
  cucumber/api/features/step_definitions/export_steps.rb
  cucumber/api/features/step_definitions/network_policy_steps.rb
  engines/conjur_audit/spec/spec_helper.rb
Labels: implementing, in progress, review
