Repository cyberark/conjur, pull requests merged in 2018-08, with the labels that each got.

#655 Export account list
  CHANGELOG.md
  cucumber/api/features/export.feature
  cucumber/api/features/step_definitions/export_steps.rb
  cucumber/api/features/support/env.rb
  lib/tasks/export.rake
Labels: in progress, review

#664 Increase Puma Worker Timeout
  CHANGELOG.md
  config/puma.rb
Labels: in progress, review

#671 OpenShift 3.3 test suite is no longer run
  Jenkinsfile
  ci/authn-k8s/dev/Dockerfile.test
  ci/authn-k8s/secrets.yml
Labels: in progress, review

#661 Configurable Export Archive Filename
  CHANGELOG.md
  bin/conjur-cli.rb
  cucumber/api/features/export.feature
  cucumber/api/features/step_definitions/export_steps.rb
  lib/tasks/export.rake
Labels: in progress, review

#680 k8s tests run tests from separate Conjur pod
  ci/authn-k8s/dev/conjurcmd.sh
  ci/authn-k8s/dev/dev_conjur.template.yaml
  ci/authn-k8s/test.sh
  ci/authn-k8s/test_gke_entrypoint.sh
  cucumber/kubernetes/features/authenticate.feature
  cucumber/kubernetes/features/login.feature
  cucumber/kubernetes/features/support/hooks.rb
Labels: in progress, review

#687 Tags published images with version number
  push-image.sh
Labels: in progress, review

#681 k8s authenticator gets client cert from HTTP_X_SSL_CLIENT_CERTIFICATE header
  Dockerfile
  app/controllers/authenticate_controller.rb
  app/domain/authentication/authn_k8s/authenticator.rb
  app/domain/authentication/strategy.rb
  ci/authn-k8s/dev/Dockerfile.nginx
  ci/authn-k8s/dev/dev_conjur.template.yaml
  ci/authn-k8s/dev/tls/default.conf
  ci/authn-k8s/dev/tls/tls.conf
  ci/authn-k8s/test.sh
  ci/authn-k8s/test_gke_entrypoint.sh
  cucumber/kubernetes/features/authenticate.feature
  cucumber/kubernetes/features/step_definitions/authenticate_steps.rb
  cucumber/kubernetes/features/step_definitions/login_steps.rb
  cucumber/kubernetes/features/support/world.rb
  spec/app/domain/authentication/strategy_spec.rb
Labels: in progress, review

#667 Update path name of conjur server container in docs
  README.md
Labels: in progress, kind/bug, kind/documentation, review

#693 Verify docker image before delete
  ci/authn-k8s/dev/utils.sh
  ci/authn-k8s/test_gke_entrypoint.sh
Labels: in progress, review

#694 Fix docker image tagging and pushing
  push-image.sh
  version_utils.sh
Labels: in progress, review

#674 Improve large policy initial load performance
  app/models/loader/orchestrate.rb
  app/models/loader/types.rb
  db/migrate/201808131137612_policy_log_trigger_bypass.rb
Labels: in progress, review

#697 Make authentication more obvious in the API documentation
  apidocs/src/authenticate.md
Labels: in progress, review

#668 Restore rubocop config
  .codeclimate.yml
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
Labels: in progress, review

#711 Updates image and link for Anchore image status badge
  README.md
Labels: review

#723 Change Sequel statement away from deprecated form
  app/controllers/authenticate_controller.rb
Labels: in progress, review

#689 Conjur CA Services
  .reek.yml
  CHANGELOG.md
  app/controllers/certificate_authority_controller.rb
  app/domain/ca/certificate_authority.rb
  config/initializers/mime_types.rb
  config/routes.rb
  cucumber/api/features/certificate_authority.feature
  cucumber/api/features/step_definitions/ca_steps.rb
  cucumber/api/features/step_definitions/request_steps.rb
  cucumber/api/features/support/ca_helpers.rb
  cucumber/api/features/support/rest_helpers.rb
  docs/AUTHENTICATORS.md
  docs/CERTIFICATE_SIGNING.md
  docs/MIGRATION.md
  docs/ROTATORS.md
Labels: in progress, review

#721 Add support for encrypted private keys in a Conjur CA
  CHANGELOG.md
  app/domain/ca/certificate_authority.rb
  cucumber/api/features/certificate_authority.feature
  cucumber/api/features/step_definitions/ca_steps.rb
  cucumber/api/features/support/ca_helpers.rb
Labels: in progress, review
