Repository cyberark/conjur, pull requests merged in 2018-11, with the labels that each got.

#776 Oidc split 2 apis
  app/controllers/authenticate_controller.rb
  app/domain/authentication/authn_oidc/authenticator.rb
  app/domain/authentication/authn_oidc/get_oidc_conjur_token.rb
  app/domain/authentication/authn_oidc/get_oidc_id_token_details.rb
  app/domain/authentication/authn_oidc/oidc_conjur_token.rb
  app/domain/authentication/authn_oidc/oidc_id_token_details.rb
  app/domain/authentication/strategy.rb
  config/routes.rb
  cucumber/authenticators/features/authn_oidc.feature
  cucumber/authenticators/features/step_definitions/authn_common_steps.rb
  cucumber/authenticators/features/step_definitions/authn_oidc_steps.rb
  cucumber/authenticators/features/support/authenticator_helpers.rb
  spec/app/domain/authentication/strategy_spec.rb
  spec/routing/authn_routing_spec.rb
Labels: in progress, review

#779 Oidc ut
  app/controllers/authenticate_controller.rb
  app/controllers/concerns/basic_authenticator.rb
  app/domain/authentication/authn_oidc/client_configuration.rb
  app/domain/authentication/authn_oidc/get_oidc_client_configuration.rb
  app/domain/authentication/authn_oidc/get_oidc_id_token_details.rb
  app/domain/authentication/authn_oidc/oidc_client.rb
  app/domain/authentication/authn_oidc/request_body.rb
  app/domain/authentication/strategy.rb
  app/domain/oidc_token_factory.rb
  config/routes.rb
  spec/app/domain/authentication/strategy_spec.rb
  spec/spec_helper.rb
Labels: in progress, review

#778 Loofah and ffi gem versions have been bumped
  CHANGELOG.md
  Gemfile
  Gemfile.lock
Labels: in progress, review

#791 Add BodyParser to HostFactoryTokensController
  app/controllers/host_factory_tokens_controller.rb
Labels: implementing, in progress, review

#794 Secure LDAP Authentication
  CHANGELOG.md
  app/domain/authentication/authn_ldap/authenticator.rb
  app/domain/authentication/authn_ldap/configuration.rb
  app/domain/authentication/authn_ldap/configuration_loader.rb
  app/domain/authentication/authn_ldap/server.rb
  app/domain/authentication/webservice.rb
  ci/authn-ldap/conjur.env
  ci/docker-compose.yml
  ci/test
  cucumber/authenticators/features/authn_ldap.feature
  cucumber/authenticators/features/step_definitions/authn_ldap_steps.rb
  cucumber/authenticators/features/support/authenticator_helpers.rb
  dev/docker-compose.yml
  dev/start
Labels: implementing, in progress, review

#797 Add CIDR hostfactory test
  app/controllers/host_factory_tokens_controller.rb
  app/models/host_factory_token.rb
  cucumber/api/features/host_factory_create_token.feature
Labels: in progress, merged, review

#798 792-bodyparser-testing
  app/controllers/concerns/body_parser.rb
  cucumber/api/features/host_factory_create_token.feature
  cucumber/api/features/step_definitions/request_steps.rb
  cucumber/api/features/support/rest_helpers.rb
Labels: implementing, in progress, review

#799 Update to revise language linking PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: implemented, in progress, review

#800 Update PR template to use Connected to
  .github/PULL_REQUEST_TEMPLATE.md
Labels: implementing, in progress, review

#801 Multi-level cert LDAP auth test
  ci/docker-compose.yml
  ci/ldap-certs/ca-chain.cert.pem
  ci/ldap-certs/ldap-server.cert.pem
  ci/ldap-certs/ldap-server.key.pem
  ci/ldap-certs/root.cert.pem
  ci/test
  cucumber/authenticators/features/support/authenticator_helpers.rb
  dev/docker-compose.yml
  dev/start
Labels: implementing, in progress, review

#805 Add audit option to the Conjur dev environment
  dev/docker-compose.yml
  dev/start
  docs/audit.md
  engines/conjur_audit/spec/db_helper.rb
Labels: implementing, in progress, review

#811 Increaased keycloak wait time to 200 second (from 100)
  ci/test
Labels: implementing, in progress, review

#809 Upgrade and pin rack to 1.6.11
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  VERSION
Labels: implementing, in progress, review

#760 add 1.3.0 diff to changelog
  CHANGELOG.md
Labels: implementing, in progress, review

#807 Add Audit tests to CI Pipeline
  .gitignore
  Jenkinsfile
  ci/docker-compose.yml
  ci/test
Labels: implementing, in progress, review
