Repository cyberark/conjur, pull requests merged in 2019-03, with the labels that each got.

#895 Extracting conjur username from id token
  app/domain/authentication/authn_oidc/authenticate.rb
  app/domain/authentication/authn_oidc/authenticate_request_body.rb
  app/domain/authentication/authn_oidc/login.rb
  app/domain/authentication/authn_oidc/login_request_body.rb
  app/domain/authentication/errors.rb
  authn-oidc-files/keycloak/create_user
  authn-oidc-files/phantomjs/fetchAuthCode
  ci/docker-compose.yml
  ci/test
  cucumber/authenticators/features/support/authenticator_helpers.rb
  dev/cli
  dev/docker-compose.yml
  dev/files/authn-ldap/ldap/ldap.ldif
  dev/start
  spec/app/domain/authentication/authn-oidc/oidc_spec.rb
Labels: implementing, in progress, review

#897 added variable for id token user property
  app/domain/authentication/authn_oidc/authenticate.rb
  app/domain/authentication/authn_oidc/client_configuration.rb
  app/domain/authentication/authn_oidc/get_oidc_client_configuration.rb
  ci/authn-oidc/keycloak/create_client
  ci/authn-oidc/keycloak/create_user
  ci/authn-oidc/keycloak/fetchCertificate
  ci/authn-oidc/keycloak/standalone.xml
  ci/authn-oidc/phantomjs/fetchAuthCode
  ci/authn-oidc/phantomjs/keycloak_login.js
  ci/authn-oidc/policy.yml
  ci/docker-compose.yml
  ci/test
  cucumber/authenticators/features/authn_oidc.feature
  cucumber/authenticators/features/authn_oidc.feature_disable
  cucumber/authenticators/features/step_definitions/authn_common_steps.rb
  cucumber/authenticators/features/support/authenticator_helpers.rb
  dev/cli
  dev/docker-compose.yml
  dev/start
  spec/app/domain/authentication/authn-oidc/oidc_spec.rb
Labels: implementing, in progress, review

#899 Fetching fixed keycloak image
  dev/docker-compose.yml
Labels: implementing, in progress, review

#904 Rearrange primary key on permissions table
  db/migrate/20190307154241_change_permissions_primary_key.rb
Labels: in progress, review, reviewing, severity/high

#913 Update readme with oidc link
  docs/AUTHENTICATORS.md
Labels: implemented

#916 fixed switch case in auth controller error handling
  app/controllers/authenticate_controller.rb
Labels: implementing, in progress

#917 This script was not permitted for execution. fixed that
  dev/files/killConjurServer
Labels: implementing, in progress

#921 Oidc cucumber infrastructure
  ci/docker-compose.yml
  ci/test
  cucumber/authenticators/features/authn_oidc.feature
  cucumber/authenticators/features/step_definitions/authn_oidc_steps.rb
  cucumber/authenticators/features/support/authenticator_helpers.rb
  cucumber/authenticators/features/support/authn_ldap_helper.rb
  cucumber/authenticators/features/support/authn_oidc_helper.rb
  dev/cli
Labels: implementing, in progress

#914 Decoding and verifying ID Token
  app/domain/authentication/authn_oidc/authenticate.rb
  app/domain/authentication/authn_oidc/authenticate_request_body.rb
  app/domain/authentication/authn_oidc/decode_and_verify_id_token.rb
  cucumber/authenticators/features/authn_oidc_login.feature_disable
  cucumber/authenticators/features/support/authn_oidc_helper.rb
  spec/app/domain/authentication/authn-oidc/oidc_spec.rb
Labels: implementing, in progress

#922 parsing id token once
  app/domain/authentication/authn_oidc/authenticate_request_body.rb
  app/domain/authentication/authn_oidc/decode_and_verify_id_token.rb
  cucumber/authenticators/features/support/authn_oidc_helper.rb
Labels: implementing, in progress

#925 Add logs of fetching keycloak authorization code, and fix pr 921 comm…
  ci/authn-oidc/phantomjs/keycloak_login.js
  cucumber/authenticators/features/authn_oidc.feature
  cucumber/authenticators/features/step_definitions/authn_oidc_steps.rb
  cucumber/authenticators/features/support/authn_oidc_helper.rb
  dev/docker-compose.yml
Labels: in progress, reviewing

#928 Change docs to a design folder
  .gitignore
  CHANGELOG.md
  README.md
  design/AUTHENTICATORS.md
  design/CERTIFICATE_SIGNING.md
  design/MIGRATION.md
  design/README.md
  design/ROTATORS.md
  design/audit.md
  design/authn_iam.md
  design/authn_ldap.md
  design/authn_oidc.md
Labels: in progress, reviewed

#926 Restructure oidc flows
  app/controllers/authenticate_controller.rb
  app/domain/authentication/authn_oidc/authenticate.rb
  app/domain/authentication/authn_oidc/authenticate_id_token/authenticate.rb
  app/domain/authentication/authn_oidc/authenticate_id_token/authenticate_request_body.rb
  app/domain/authentication/authn_oidc/authenticate_id_token/decode_and_verify_id_token.rb
  app/domain/authentication/authn_oidc/authenticate_oidc_conjur_token.rb
  app/domain/authentication/authn_oidc/authenticate_oidc_conjur_token/authenticate_oidc_conjur_token.rb
  app/domain/authentication/authn_oidc/authenticate_oidc_conjur_token/validate_and_decrypt_oidc_conjur_token.rb
  app/domain/authentication/authn_oidc/authenticate_request_body.rb
  app/domain/authentication/authn_oidc/authenticator.rb
  app/domain/authentication/authn_oidc/client.rb
  app/domain/authentication/authn_oidc/decode_and_verify_id_token.rb
  app/domain/authentication/authn_oidc/fetch_oidc_secrets.rb
  app/domain/authentication/authn_oidc/get_conjur_oidc_token/authenticator.rb
  app/domain/authentication/authn_oidc/get_conjur_oidc_token/client.rb
  app/domain/authentication/authn_oidc/get_conjur_oidc_token/conjur_oidc_token.rb
  app/domain/authentication/authn_oidc/get_conjur_oidc_token/id_token_details.rb
  app/domain/authentication/authn_oidc/get_conjur_oidc_token/login_request_body.rb
  app/domain/authentication/authn_oidc/get_oidc_conjur_token.rb
  app/domain/authentication/authn_oidc/id_token_details.rb
  app/domain/authentication/authn_oidc/login.rb
  app/domain/authentication/authn_oidc/login_request_body.rb
  app/domain/authentication/authn_oidc/util/fetch_oidc_secrets.rb
  app/domain/oidc_token_factory.rb
  spec/app/domain/authentication/authn-oidc/oidc_authenticate_id_token_spec.rb
  spec/app/domain/authentication/authn-oidc/oidc_authenticate_oidc_conjur_token_spec.rb
  spec/app/domain/authentication/authn-oidc/oidc_login_spec.rb
  spec/app/domain/authentication/authn-oidc/oidc_spec.rb
  spec/support/oidc_spec_helper.rb
Labels: implementing, in progress

#936 Refactored some command classes to fit standard
  app/domain/authentication/audit_event.rb
  app/domain/authentication/authenticate.rb
  app/domain/authentication/authn_oidc/authenticate_id_token/authenticate.rb
  app/domain/authentication/authn_oidc/authenticate_oidc_conjur_token/authenticate_oidc_conjur_token.rb
  app/domain/authentication/authn_oidc/get_conjur_oidc_token/conjur_oidc_token.rb
  app/domain/authentication/login.rb
Labels: in progress, reviewing

#934 Oidc tests
  app/controllers/application_controller.rb
  app/controllers/authenticate_controller.rb
  app/domain/authentication/authn_oidc/authenticate_id_token/authenticate_request_body.rb
  app/domain/authentication/errors.rb
  ci/authn-oidc/keycloak/create_user
  ci/authn-oidc/phantomjs/fetchAuthCode
  ci/docker-compose.yml
  ci/test
  cucumber/authenticators/features/authn_oidc.feature
  cucumber/authenticators/features/step_definitions/authn_ldap_steps.rb
  cucumber/authenticators/features/step_definitions/authn_oidc_steps.rb
  cucumber/authenticators/features/support/authenticator_helpers.rb
  cucumber/authenticators/features/support/authn_oidc_helper.rb
  dev/cli
  dev/docker-compose.yml
  dev/start
Labels: implementing, in progress

#937 Update bootstrap-sass, remove dependency on jessie-updates
  Gemfile.lock
  ci/authn-k8s/dev/Dockerfile.test
Labels: implementing, in progress

#938 Oidc tests
  ci/test
Labels: implementing, in progress
